### ISSUE TITLE
Model retraining / crossvalidation

### ISSUE THREAD

**Issue by nanopony** [ethgasstation/ethgasstation-backend#24] opened 2018-06-25 09:03 UTC
Hello!

FIrst of all, thank you for sharing the code of such an important project -- it means a lot both for cryptoenthusiasts and open source community.

The file `model_gas.py`  is addressing the `minedtx2` table, the last reference to which was removed with 7ed90ad2fc07883866c5974c6717fcc428be8933 commit.

**Comment by 10a7** [comment] 2018-07-13 02:16
cc @ethgasstation, regression due to the refactor.

**Comment by ethgasstation** [comment] 2018-07-13 02:52
Fixed with 3b41dcce67c7aa3d636ce2ae2da45c832c42001e

**Closed by ethgasstation** 2018-07-13 02:52 UTC
